# Generated by Django 5.1.4 on 2024-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit_and_blow_playerscore',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
