# Generated by Django 5.1.4 on 2024-12-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_card_created_by_alter_cardeffect_target_type'),
    ]

    operations = [

    ]
