# Generated by Django 5.1.4 on 2024-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_remove_card_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffect',
            name='var',
            field=models.IntegerField(default=0),
        ),
    ]
