# Generated by Django 5.1.4 on 2024-12-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_cardeffect_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffect',
            name='target_type',
            field=models.IntegerField(),
        ),
    ]
