# Generated by Django 5.1.4 on 2024-12-16 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0007_remove_deck_cards_carddeck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cardgame.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cardgame.deck')),
            ],
        ),
        migrations.CreateModel(
            name='CardEffectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.IntegerField(default=0)),
                ('card_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card_effects', to='cardgame.cardeffect')),
                ('deck_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_effects', to='cardgame.deckcard')),
            ],
        ),
        migrations.DeleteModel(
            name='CardDeck',
        ),
    ]
