# Generated by Django 5.1.4 on 2024-12-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0008_remove_deck_created_at_remove_deck_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeckCard',
            new_name='CardDeck',
        ),
    ]
