# Generated by Django 5.1.4 on 2024-12-19 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0009_rename_deckcard_carddeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mana', models.PositiveIntegerField(default=10)),
                ('mana_recovery', models.PositiveIntegerField(default=1)),
                ('turn_time_limit', models.PositiveIntegerField(default=60)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_rule', to='cardgame.session')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.PositiveIntegerField(default=0)),
                ('preparation_time_left', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='cardgame.session')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='cardgame.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='cardgame.session')),
            ],
        ),
    ]
