# Generated by Django 5.0 on 2025-01-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0010_gamerule_gamestate_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='turn_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='cardgame.player'),
        ),
    ]
