# Generated by Django 5.0 on 2025-01-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0012_alter_session_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
