# Generated by Django 5.0 on 2025-01-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0013_alter_player_health_alter_player_mana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
