# Generated by Django 5.0 on 2025-01-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0014_alter_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='turn_proceccing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='mana',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_mana',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
