# Generated by Django 5.0 on 2025-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0015_session_turn_proceccing_alter_session_mana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
