# Generated by Django 5.0 on 2025-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0016_alter_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deck_id',
            field=models.IntegerField(default=0),
        ),
    ]
